#page title
page_title                                :  # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 361309726                              # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
spanish_page_link                         : https://es.papakoala.com                                                                                      

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_subtitle                              : Early stimulation exercises for babies.
app_description                           : Newborns crave novelty and become bored with familiarity, so their eyes, ears, and other sensory organs are attuned to events from which they can learn.<br />PapaKoala features more than 70 videos with detailed explanations to foster their own development. <br />Additional activities from age one through age two will come in a future app update.
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : PapaKoala                                
your_link                                 : https://papakoala.com                     
your_city                                 :                              
email_address                             : hello@papakoala.com
facebook_username                         :                                           
instagram_username                        : papakoala_en
twitter_username                          : unpapakoala
github_username                           : 
youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Create an environment to foster brain development
    description                           : The early years are a period of considerable opportunity for growth. Babies who have more sensory experiences are able to develop more brain power.³
    fontawesome_icon_name                 : brain
    
  - title                                 : Enriched with early sensory experiences
    description                           : During the first year of life, babies are developing incipient theories about how the world operates. These foundational theories play a profound role in children's everyday lives and subsequent education.²
    fontawesome_icon_name                 : baby

  - title                                 : #Develop more brain power
    description                           : # A child’s experiences and environment during his ﬁrst three years play a crucial role in determining the course of his later life.¹
    fontawesome_icon_name                 : # puzzle-piece

  - title                                 : #Provide sensitive caregiving activities
    description                           : #These are the most essential catalysts for feats of intellectual growth. Healthy brain development relies on people to provide the stimulation that organizes connections in the cortex for language and complex thought.
    fontawesome_icon_name                 : #heart

  - title                                 : Develop deep attachments
    description                           : PapaKoala's activities support nurturing relationships which favour the foundation for positive relationships with peers and teachers, healthy self-concept, and emotional and moral understanding.
    fontawesome_icon_name                 : heart

  - title                                 : #From birth through age one
    description                           : #Newborns crave novelty and become bored with familiarity, so their eyes, ears, and other sensory organs are attuned to events from which they can learn. PapaKoala features more than 70 videos with detailed explanations. Additional activities from age one through age two will come in a future app update.
    fontawesome_icon_name                 : #child

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#6EC8FF"
topbar_transparency                       : 0.4
topbar_title_color                        : "#444B54"

cover_image                               : assets/header_lowres.jpg                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#444B54"

app_title_color                           : "#444B54"
app_price_color                           : "#FFFFFF"
app_description_color                     : "#ffffff"

app-language-color                        : "#FFEAC1"

feature_title_color                       : "#6EC8FF"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#FA6694"

social_icons_foreground_color             : "#7cc6fe"
social_icons_background_color             : "#FFFFFF"

footer_text_color                         : "#FA6694"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
