###### Translations here #######

# SEO
title: PapaKoala: Exercices de stimulation précoce pour bébés, faciles à réaliser
tagline: Exercices de stimulation précoce pour bébés, faciles à réaliser
description: Activités de stimulation précoce pour les bébés afin de favoriser le développement du cerveau, de fournir des expériences sensorielles précoces et de créer un sentiment de confiance.

# page title
page_title: Cultivez votre petit génie: Découvrez le parcours de stimulation précoce de PapaKoala
app_name: PapaKoala: Développement du nouveau-né
app_price: Basé sur un abonnement
app_subtitle: Embarquez dans un voyage de puissance cérébrale et de connexion avec PapaKoala pour les bébés de 0 à 1 an.
app_description: "Les premières années sont une fenêtre d'opportunité exceptionnelle pour le développement du cerveau d'un bébé. C'est le moment idéal pour allumer leur potentiel intellectuel et jeter les bases d'un apprentissage à vie.\nPapaKoala, votre guide personnel de stimulation précoce, vous permet de nourrir la croissance cognitive de votre tout-petit et de créer une profonde connexion émotionnelle avec lui."

# Caractéristiques              Editez, ajoutez ou supprimez des fonctionnalités à présenter.
features:
    - title: Libérez le pouvoir de la stimulation précoce
      description: Immergez votre bébé dans un monde d'expériences stimulantes qui favorisent son développement cérébral et éveillent ses sens. Les activités soigneusement sélectionnées de PapaKoala, guidées par des recherches développementales expertes, introduisent votre petit à une symphonie de couleurs, de sons et de toucher, stimulant ses voies neurales et posant les bases du succès futur.
      fontawesome_icon_name: baby

    - title: Découvrez le plaisir de l'apprentissage interactif
      description: Dites adieu aux exercices monotones et adoptez la nature amusante et engageante des activités interactives de PapaKoala. Nos tutoriels vidéo basés sur des vidéos fournissent des directives claires et rendent l'apprentissage une expérience agréable pour les parents et les bébés.
      fontawesome_icon_name: brain

    - title: Nourritez un lien d'amour et de confiance
      description: La stimulation précoce ne se limite pas au développement cognitif; il s'agit de créer un lien sécurisant et aimant entre vous et votre bébé. Les activités de PapaKoala mettent l'accent sur le toucher, la forme la plus fondamentale d'engagement d'un enfant, favorisant la confiance, la sécurité et une profonde connexion émotionnelle.
      fontawesome_icon_name: heart



############## end of translations block #####





# App Info
ios_app_id                                : 1540490806                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
spanish_page_link                         : https://es.papakoala.com                                                                                      
japan_page_link                           : https://jap.papakoala.com
english_page_link                         : https://papakoala.com  
chinese_page_link                         : https://cn.papakoala.com
german_page_link                          : https://ger.papakoala.com
southkorea_page_link                      : https://kor.papakoala.com
french_page_link                          : https://fr.papakoala.com
italian_page_link                         : https://it.papakoala.com
hindi_page_link                           : https://hi.papakoala.com
portuguese_page_link                      : https://pt.papakoala.com
brazil_page_link                          : https://ptbra.papakoala.com

app_icon                                  :                      # assets/appicon.png  Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : PapaKoala                                
your_link                                 : https://papakoala.com                     
your_city                                 :                              
email_address                             : hello@papakoala.com
facebook_username                         :                                           
instagram_username                        : papakoala_app
twitter_username                          : 
github_username                           : 
youtube_username                          : 




# Theme Settings
topbar_color                              : "#6EC8FF"
topbar_transparency                       : 0.4
topbar_title_color                        : "#444B54"

cover_image                               : assets/header_lowres.jpg                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FFEAC1"

app_title_color                           : "#393e44"
app_price_color                           : "#FFFFFF"
app_description_color                     : "#ffffff"

app_language_color                        : "#FFEAC1"

feature_title_color                       : "#FFEAC1"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#FA6694"

social_icons_foreground_color             : "#BF82EC"
social_icons_background_color             : "#FFFFFF"

footer_text_color                         : "#000000"




# Google services
google_analytics: G-D89JL3TSP6




# url: papakoala.com




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
